### ISSUE TITLE
I have  confused  dapr in kubernetes   about service invoke.

### ISSUE THREAD

**Issue by a121984376** [dapr/samples#101]
in kunernetes  normal servie invoke  like this:
![image](https://user-images.githubusercontent.com/15758574/160233134-6863fcb7-bc02-4215-8dbe-38ca9d50cae5.png)

Now use dapr. there is sidecar with pod2.   How pod1 invoke pod2?  what`s the  pod2  service address ? 

pod1 invoke pod2`s sidecar? or pod2` svc name?
like this ???
![image](https://user-images.githubusercontent.com/15758574/160233301-28d7dc43-1c9b-4b59-b9c8-b4b80fec20da.png)

or 
![image](https://user-images.githubusercontent.com/15758574/160233326-e21b6cd5-035c-4bff-a5b2-be2fd7a60d83.png)

**Comment by yaron2** [comment]
It's app 1 --> sidecar 1 --------> sidecar 2 --> app2

I suggest to read more here: https://docs.dapr.io/developing-applications/building-blocks/service-invocation/service-invocation-overview/

**Comment by a121984376** [comment]
> It's app 1 --> sidecar 1 --------> sidecar 2 --> app2
> 
> I suggest to read more here: https://docs.dapr.io/developing-applications/building-blocks/service-invocation/service-invocation-overview/

thanks
