### ISSUE TITLE
error invoking output binding sample-topic: couldn't find output binding sample-topic"

### ISSUE THREAD

**Issue by trumhemcut** [dapr/samples#105]
## Expected Behavior
```
...
{'data': {'orderId': 240}}
<Response [200]>
{'data': {'orderId': 241}}
<Response [200]>
...
```

## Actual Behavior

```
{'data': {'orderId': 830}}
{"errorCode":"ERR_INVOKE_OUTPUT_BINDING","message":"error invoking output binding sample-topic: couldn't find output binding sample-topic"}
```

## Steps to Reproduce the Problem
Follow the README of bindings example for Kubernetes:

1. Create Kafka cluster & create a kafka client pod & create a *sample* topic
2. Deploy the microservices (by ```kubectl apply -f .```)
3. ```kubectl logs bindings-pythonapp-644489969b-c8lg5``` and get above error

How do we check if the binding component is working with with Kafka cluster?

**Comment by tylertechgraves** [comment]
I can also attest to this being an issue.  I've tried everything I could think of to debug/fix the issue, but I continue to get the exact same results detailed by @trumhemcut when running the sample code in a docker desktop kubernetes cluster.

Docker version:  2.1.0.5 (40693)
K8S version:  1.14.8

**Comment by artursouza** [comment]
I faced similar issue while trying this sample using a 3-node AKS cluster. Here are the steps I took to resolve it:
0. Delete the app deployments (keep kafka, in the mean time): kubectl delete -f ./5.bindings/deploy/

1. Check which is the advertised service for the kafka and zookeeper: kubectl get svc
NAME                            TYPE           CLUSTER-IP     EXTERNAL-IP     PORT(S)                      AGE
bindings-nodeapp                LoadBalancer   10.0.54.207    <HIDDEN>   80:31978/TCP                 7m19s
bindings-nodeapp-dapr           ClusterIP      10.0.16.123    <none>          80/TCP,50001/TCP             7m18s
bindings-pythonapp-dapr         ClusterIP      10.0.237.248   <none>          80/TCP,50001/TCP             7m18s
dapr-api                        ClusterIP      10.0.17.51     <none>          80/TCP                       2d20h
dapr-kafka  <===THIS!!!   ClusterIP      10.0.15.41     <none>          9092/TCP                     42h 
dapr-kafka-headless           ClusterIP      None           <none>          9092/TCP                     42h
dapr-kafka-zookeeper  <===== THIS!            ClusterIP      10.0.247.96    <none>          2181/TCP                     42h
dapr-kafka-zookeeper-headless   ClusterIP      None           <none>          2181/TCP,3888/TCP,2888/TCP   42h
dapr-placement                  ClusterIP      10.0.53.43     <none>          80/TCP                       2d20h
dapr-sidecar-injector           ClusterIP      10.0.173.248   <none>          443/TCP                      2d20h
kubernetes                      ClusterIP      10.0.0.1       <none>          443/TCP                      4d1h
redis-headless                  ClusterIP      None           <none>          6379/TCP                     2d20h
redis-master                    ClusterIP      10.0.106.37    <none>          6379/TCP                     2d20h
redis-slave                     ClusterIP      10.0.99.132    <none>          6379/TCP                     2d20h

In my case, it is called dapr-kafka. Notice that it is all running in the default namespace.

2. Test the kafka pub-sub (no dapr involved yet, but pay attention to the endpoints for kafka and zookeeper in the commands):
Create a kafka topic just for this test:
kubectl exec testclient -- kafka-topics --zookeeper dapr-kafka-zookeeper:2181 --topic test--create --partitions 1 --replication-factor 1
Have two new terminals open and play with the standard console pub/sub test:
Terminal 1: kubectl exec -ti testclient -- kafka-console-consumer --bootstrap-server dapr-kafka:9092 --topic sample --from-beginning
Terminal 2: kubectl exec -ti testclient -- kafka-console-producer --broker-list dapr-kafka:9092 --topic asouza
Enter any text on terminal 2 and hit enter. You will see how it also shows up on terminal 1. If this test does not work, you might want to delete all deployments and start the sample over again.

3. Change the binding's settings to match your service endpoint for kafka:
Edit 5.bindings/deploy/kafka_bindings.yaml and update the brokers setting to match your kafka endpoint. This is how mine looks:
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: sample-topic
spec:
  type: bindings.kafka
  metadata:
  # Kafka broker connection setting
  - name: brokers
    value: dapr-kafka:9092
  # consumer configuration: topic and consumer group
  - name: topics
    value: sample
  - name: consumerGroup
    value: group1
  # publisher configuration: topic
  - name: publishTopic
    value: sample
  - name: authRequired
    value: "false"

Now continue the sample from here: https://github.com/dapr/samples/tree/master/5.bindings#deploy-assets

Please, let me know if any of this works and what was the difference that made it work. In my case, it was the broker endpoint.

**Comment by trumhemcut** [comment]
![image](https://user-images.githubusercontent.com/5198341/69492256-c8065280-0ed2-11ea-9d59-2862931fa54d.png)
Following the steps here, it will create Kafka cluster with namespace *kafka*, so the step of @artursouza  looks not running well in my case.

**Comment by trumhemcut** [comment]
I pulled the latest code example and it works well for now :) 

Thanks & close for now. I see 

```  
    - name: authRequired
      value: "false"
```
in the *binings.kafka* component

![image](https://user-images.githubusercontent.com/5198341/69493261-57b1fe00-0edf-11ea-8109-b4ce9efe9545.png)
