### ISSUE TITLE
Support listing of external samples

### ISSUE THREAD

**Issue by mchmarny** [dapr/samples#12]
There is [a number](https://github.com/search?q=dapr+sample&type=Repositories) of Dapr samples [all over GitHub](https://github.com/search?q=dapr+sample&type=Repositories). Given the existing disclaimer about each sample being maintainer by its author, the `dapr/samples` repo should allow for listing of external samples, ones located in user's repo. 

Here are some arguments for this approach: 

* Maintainability over time
* Users clone only the repo for the sample they want to use (not repo of many samples) 
* Ability to support integrations (e.g. Dockerfile or GitHub actions in root)

This approach would still allow for curated list of samples and the `dapr/samples` repo would still be the go-to place for listing of Dapr demos/samples. 

Few popular examples of this approach:

* https://github.com/steren/awesome-cloudrun
* https://github.com/akullpp/awesome-java
* https://github.com/vuejs/awesome-vue
* https://github.com/avelino/awesome-go
* https://github.com/enaqx/awesome-react
* https://github.com/sindresorhus/awesome-nodejs

**Comment by orizohar** [comment]
Yes, this is the intent of the [External Samples](https://github.com/dapr/samples#external-samples) section in the main README

**Comment by mchmarny** [comment]
I've PR go templates to this section. We should probably list a few other external samples. May be worth review [these](https://github.com/search?q=dapr+sample&type=Repositories)

**Comment by AaronCrawfis** [comment]
I agree with the External Samples section and letting contributors link to examples that exist outside the repo. Although we may need to pen some guidance on how a contributor will decide where to place his/her code. I envision confusion on where samples should be placed and what's best practice.

**Comment by AaronCrawfis** [comment]
Also should the primary list of samples be in the samples README or the Dapr docs (& the upcoming docs.dapr.io site)? I vote to make the samples README be a pointer to the docs site so that it's on a site that better support readability for long lists and users can easily search for products/services and discover samples using that search box

**Comment by mchmarny** [comment]
> should the primary list of samples be in the samples README or the Dapr docs

Interesting question

**Comment by msfussell** [comment]
Added external samples section
