### ISSUE TITLE
Outdated readme.MD in samples/1.hello-world/

### ISSUE THREAD

**Issue by CharlieZ-Autodesk** [dapr/samples#125]
## Expected Behavior

In dapr/samples/1.hello-world/readme.MD, step 4, the example command "dapr invoke ..." does not work, only "dapr send ..." works.

## Actual Behavior

"dapr invoke ..." command returns error, _unknown command "invoke" for "dapr"_

## Steps to Reproduce the Problem

Try the "dapr invoke ..." commands listed in readme.MD step 4 to see the error message.

**Comment by youngbupark** [comment]
@CharlieZ-Autodesk Can you please run one-liner command to install the latest cli ?

**Comment by charliezgc** [comment]
I opened this issue under a different login. Yes, the latest cli solves this issue. The issue can be closed.
