### ISSUE TITLE
Problem in "samples/2.hello-kubernetes/"

### ISSUE THREAD

**Issue by Shawn-Fan** [dapr/samples#132]
Followed the instruction "https://github.com/dapr/samples/tree/master/2.hello-kubernetes":
......
Step 2 - Create and Configure a State Store
Dapr can use a number of different state stores (Redis, CosmosDB, DynamoDB, Cassandra, etc.) to persist and retrieve state. For this demo, we'll use Redis.

Follow these steps to create a Redis store.
......
I tried several times to install redis in macos, Unfortunitely, it didn't  work, could you let me know how to do it?

Thanks,

**Comment by lomholdt** [comment]
The sample you are mentioning is a Kubernetes hello world. It should not matter that you are on macOS to make Redis work. Can you describe what you did that didn't work?

**Comment by Shawn-Fan** [comment]
Thanks for your reply(I have not tried it since then). 
As what I remembered I followed the instruction from https://github.com/dapr/docs/blob/master/concepts/components/redis.md#creating-a-redis-store
but it didn't work.

**Comment by youngbupark** [comment]
@Shawn-Fan are you using minikube to run sample 2 ? can you check if redis server is running ? 
```
youngp@Youngs-MBP react-calculator % kubectl get pods
NAME             READY   STATUS              RESTARTS   AGE
redis-master-0   0/1     ContainerCreating   0          6s
redis-slave-0    0/1     ContainerCreating   0          6s
```

**Comment by Shawn-Fan** [comment]
@youngbupark  In January, I installed Redis into the cluster (helm install stable/redis --name redis)  error message showed up. I just noticed something changed in the document maybe I should try it late. 
Thanks in advance!
