### ISSUE TITLE
Clarify instructions for sample 2 hello.kubernetes

### ISSUE THREAD

**Issue by pelithne** [dapr/samples#136]
Some of the instructions in the sample could be more clear. Below follows a few suggested edits

* In Prerequisites, it should be stated that the repo should be cloned with ````git clone https://github.com/dapr/samples.git````. This would help users who are trying to run just one sample, and who may not have read the "main" README.

* In Step 1, this statement is confusing:
"Once you have a cluster, follow [these steps](https://github.com/dapr/docs/blob/master/getting-started/environment-setup.md#installing-dapr-on-a-kubernetes-cluster) to deploy Dapr to it". The reason its conifusing is that you do not need to follow the link for the instructions, since they are actually included in the README.

* In Step 2, there´s a minor formatting error. Change this: "Dapr can use a number of different state stores (Redis, CosmosDB, DynamoDB, Cassandra, etc.) " to this "Dapr can use a number of different state stores (Redis, CosmosDB, DynamoDB, Cassandra, etc)". 

I can make a PR with the suggested changes.

**Comment by youngbupark** [comment]
@pelithne make sense, please create PR.
