### ISSUE TITLE
Build and publish images for Arm architectures

### ISSUE THREAD

**Issue by MikeLarah** [dapr/samples#137]
## Describe the proposal

Currently docker images for the samples are built for amd64 architecture only. If using multi-arch build to target Arm architectures, then samples can be deployed to devices such as Raspberry Pi.

**Comment by msfussell** [comment]
YoungBu. Has this now been resolved in the CLI for upcoming release? (v0.5.0 runtime)

**Comment by youngbupark** [comment]
> YoungBu. Has this now been resolved in the CLI for upcoming release? (v0.5.0 runtime)

No he is asking about building sample docker image for arm. we don't support it.

**Comment by msfussell** [comment]
Samples are expected to show how to do something and will not run on all platforms.
