### ISSUE TITLE
Dockerfiles COPY non existent file path

### ISSUE THREAD

**Issue by jjcollinge** [dapr/samples#139]
## Expected Behavior
Following the [Next Steps](https://github.com/dapr/samples/tree/master/2.hello-kubernetes#next-steps) instructions in `2.hello-kubernetes`, it describes how you can navigate to the app directory (node|python) and build the docker image.

## Actual Behavior
However, the Dockerfiles uses the `COPY .dockerfiles` line to copy the source into the image. This file doesn't exist so you get the following error:
```
COPY failed: stat /var/lib/docker/tmp/docker-builder558678560/.dockerfiles: no such file or directory
```

I guess this is because the _actual_ expected process is to create a symlink at the repo root using:
```
ln -s 1.hello-world/ .dockerfiles
```
and then build the docker image using:
```
docker build -f 2.hello-kubernetes/node/Dockerfile .
```

## Steps to Reproduce the Problem
Follow the [Next Steps](https://github.com/dapr/samples/tree/master/2.hello-kubernetes#next-steps) instructions to build a custom image.

**Comment by youngbupark** [comment]
Closing #149
