### ISSUE TITLE
Update samples to support multiple state stores

### ISSUE THREAD

**Issue by jjcollinge** [dapr/samples#140]
## Expected Behavior
The latest samples work with latest Dapr.

## Actual Behavior

The sample apps error as the state URL has a breaking change in latest Dapr that support multiple state stores.

This can be fixed by changing the `stateUrl` from:
`.../v1.0/state/` to `.../v1.0/state/statestore` but assumes the state store component used the name `statestore`.

## Steps to Reproduce the Problem
Run the `1.hello-world` sample with the latest version of the Dapr runtime.

**Comment by yaron2** [comment]
@amanbha can we close this?

**Comment by amanbha** [comment]
yes.
