### ISSUE TITLE
daprd.exe and node.js process stay running after running dapr stop

### ISSUE THREAD

**Issue by genbod** [dapr/samples#141]
## Expected Behavior

if I run dapr stop, then the node.js process that is running should stop.  If I run dapr uninstall, daprd.exe should stop. 

## Actual Behavior

node.js process continues running so a subsequent dapr run will throw errors because the port is in use.  If I spin up a kube version and daprd is already running then I can't communicate to the docker service because the dapr port is still in use (i.e. if I am trying to port forward into the dapr sidecar etc.)  It doesn't matter if I run as administrator or not.

## Steps to Reproduce the Problem

Windows 10 Pro18362.592
Node.js v12.14.1
dapr 0.3.0

run sample 1.  run dapr stop node.  run dapr start node.  Notice error and old node process still running.

**Comment by youngbupark** [comment]
@genbod This issue should fix in the next release (v0.4.0) by https://github.com/dapr/cli/pull/246

**Comment by youngbupark** [comment]
@genbod This must be fixed. please reinstall Dapr cli 0.4.0 using one liner install script
