### ISSUE TITLE
Java Sample using DAPR on AKS

### ISSUE THREAD

**Issue by ross-p-smith** [dapr/samples#149]
Hi there, we carried out some upskilling in Dapr for a project using Java Microservices architecture and wondered if it was a good fit to live under your samples? Happy to have a chat as we have a few weeks of wrapping up our project that we could lean in and shape the sample

You can have a look at it here: - https://github.com/mahmutcanga/java-banking-pubsub-dapr-sample

We are also thinking about putting this in Azure Samples - but would love a reach out!

**Comment by msfussell** [comment]
@ross-p-smith - We would also be open to including code in Samples. Or you can choose to link this from the Readme, if you have found a home for this code where you are maintaining this.

**Comment by ross-p-smith** [comment]
Hope you are well @msfussell! Added a link to the readme - it ended up in Azure-Samples

**Comment by msfussell** [comment]
Excellent indeed! Thanks for adding this!
