### ISSUE TITLE
Updating csharp distributed calculator to .NET Core 3.1

### ISSUE THREAD

**Issue by samueleresca** [dapr/samples#155]
Can I proceed by opening a PR that migrates the sample CSharp projects into .NET Core 3.1?

**Comment by youngbupark** [comment]
@amanbha can answer this question.

**Comment by amanbha** [comment]
@samueleresca sorry, for the delay in answering this, yes, you can create a PR to upgrade these to net core 3.1 Thanks!. I am assigning the issue to you.

**Comment by msfussell** [comment]
@samueleresca  - Can you still work on this?

**Comment by samueleresca** [comment]
Hi @msfussell, I've opened a PR related to the issue.

**Comment by amanbha** [comment]
Thanks foor the contribution @samueleresca . I have merged the PR.
