### ISSUE TITLE
Proposal: Sample for showcasing new Dapr 1.10/1.11 capabilities (Workflows + External Invocation Support) 

### ISSUE THREAD

**Issue by kendallroden** [dapr/samples#158]
Adding a community sample that showcases a more comprehensive sample using the Workflow API and an external, non-Dapr endpoint call would be valuable to help people understand how the features work together, and also showcase practically how to use them for a more "real-world" scenario.

**Comment by kendallroden** [comment]
Fulfilled by PR #159

**Comment by msfussell** [comment]
Complete
