### ISSUE TITLE
State Persistance not working locally in 1.hello-world 

### ISSUE THREAD

**Issue by Keithalisk** [dapr/samples#158]
## Expected Behavior

I expected the tokens to be replaced in http://localhost:${daprPort}/v1.0/state/${stateStoreName}
but console log shows:   Got a new order! Order ID: 41
 Body {
 url: 'http://localhost:${daprPort}/v1.0/state/${stateStoreName}',
 status: 404,
 statusText: 'Not Found',

Hard-coding both strings resulted in:
Got a new order! Order ID: 41
Body {
 url: 'http://localhost:3500/v1.0/state/statestore',
 status: 405,
 statusText: 'Method Not Allowed',

Only after I removed the statestore from the path did it persist the state: 
Got a new order! Order ID: 41
 Successfully persisted state.

## Actual Behavior

The string tokens were not replace, and when I replaced them manually, the endpoint was not found.   

## Steps to Reproduce the Problem

Simply run the sample 1.hello-world code in the current branch against the current runtime locally.

**Comment by amanbha** [comment]
@Keithalisk We have introduced a breaking change for state management api with 0.4.0 release.
What is the version of dapr runtime you are using. You can get it by running cli command: dapr --version

**Comment by Keithalisk** [comment]
I'm was using 0.3.0 of the cli and runtime.  I didn't realize 0.4 had been
released.  What is the best way to get visibility into when updates are
pushed?

Thanks,

Keith

**Comment by amanbha** [comment]
@Keithalisk We try to minimize breaking changes and there wont be any breaking changes once we hit 1.0.

We include breaking change info in our release announcement https://github.com/dapr/dapr/releases/tag/v0.4.0
