### ISSUE TITLE
Need to add a warning about non-default namespace usage in Hello Kubernetes sample

### ISSUE THREAD

**Issue by srntqn** [dapr/samples#159]
I think, for better understanding, "Hello Kubernetes" [README.md](https://github.com/dapr/samples/blob/master/2.hello-kubernetes/README.md) should have the same warning about non-default namespace usage as the other docs. It allows to avoid misunderstanding and provide a clear consistent documentation. 

[Example of warning.](https://github.com/dapr/docs/blob/master/getting-started/environment-setup.md#using-the-dapr-cli)

For now  readme doesn't have this warning and it can lead to errors during Dapr's deployment.

**Comment by amanbha** [comment]
@srntqn woudl you like to submit a PR for this?

**Comment by srntqn** [comment]
@amanbha yes, sure.

**Comment by msfussell** [comment]
@srntqn - Any update here on this PR?

**Comment by srntqn** [comment]
@msfussell @amanbha sorry for the delay. I've made a PR.

**Comment by amanbha** [comment]
Thanks for the contribution @srntqn I have merged the PR.
