### ISSUE TITLE
Add a sample for multiple state stores

### ISSUE THREAD

**Issue by pruthvidhodda** [dapr/samples#160]
## Describe the proposal

It'd be nice to have a sample showcasing the multiple state store handling capability of dapr.

**Comment by codeputer** [comment]
It would also be good to define what multi-state store handling is, and why it's important as a feature in Dapr... at least that is what I'm wondering.  I'm assuming this is for Actors, and why would an Actor instance what to use it?

**Comment by amanbha** [comment]
@pruthvidhodda multiple state store is just an artifact of how state management is done with Dapr, it doesnt need a new sample.
@codeputer  Actors dont use multiple state stores.


I am closing this usse, please feel free to reopen if you have more questions
