### ISSUE TITLE
Node js subscriber does not work in PubSub example

### ISSUE THREAD

**Issue by artursouza** [dapr/samples#166]
## Expected Behavior

ℹ️  Updating metadata for app command: node app.js
✅  You're up and running! Both Dapr and your app logs will appear here.

== APP == A:  {'id': '98a340d6-d101-49b7-98ff-bda92adbe682', 'source': 'node-subscriber', 'type': 'com.dapr.event.sent', 'specversion': '0.3', 'datacontenttype': 'application/json', 'data': {'message': 'This is a test'}, 'subject': ''}

## Actual Behavior

ℹ️  Updating metadata for app command: node app.js
✅  You're up and running! Both Dapr and your app logs will appear here.

== APP == A:  {}

## Steps to Reproduce the Problem

Run pubsub sample in sandalone mode. After publishing the first message, you can see that python subscriber gets the complete JSON while the node app gets an empty JSON.

**Comment by yaron2** [comment]
Fixed with https://github.com/dapr/dapr/issues/1248
