### ISSUE TITLE
Run Distributed Calculator Locally?

### ISSUE THREAD

**Issue by cwiederspan** [dapr/samples#172]
Is it possible to get Sample 3, the Distributed Calculator, to run locally?

I ask because it is my perception that to run locally, I would need to run several different _dapr run_ commands to spin this up. For example, something like this...

```bash
dapr run --app-id addapp --app-port 6000 --port 3501 ...
dapr run --app-id subtractapp --app-port 80 --port 3502 ...
...
dapr run --app-id calculator-front-end --app-port 8080 --port 3510 ...
```

Specifically, if I understand correctly, the **--port XXXX** would have to be different for every service that I'm running, and thus, the react-calculator app would need to be retooled to support multiple DAPR_HTTP_PORT values.

Please note that I'm not actually trying to get this to run locally as much as I'm trying to make sure I understand the concept of using the standalone functionality in a multi-service scenario.

In any case, if I'm am thinking about this right, it seems that the local capabilities essentially defeat the purpose of the service discovery of dapr because I need to associate port numbers to each service.

Hopefully I'm just missing something, so I'd love some insight to confirm whether that's the case.

**Comment by amanbha** [comment]
You just need to provide different port for --port as "dapr run" cli command starts dapr listening on that port.
react calculator app doesn't need to be retooled to support multiple http ports, it will talk to its dapr sidecar which will then route calls correctly to other services.

**Comment by amanbha** [comment]
@cwiederspan I am closing it for now, feel free to reopen if you have any further questions regarding this

**Comment by cwiederspan** [comment]
Thanks, I was actually able to get the calculator running locally and learned some things along the way. @amanbha - thanks for the shove in the right direction.
