### ISSUE TITLE
Make 1.hello-world consistent with 2.hello-kubernetes

### ISSUE THREAD

**Issue by ryanvolum** [dapr/samples#18]
Both samples should use the same two microservices with identical code:

- [ ] Update 1.hello-world node app to have the same code as 2.hello-kubernetes node app
- [ ] Add python app from 2.hello-kubernetes to 1.hello-world
- [ ] Update 1.hello-world instructions to run both microservices

**Comment by yaron2** [comment]
cc @ryanvolum
