### ISSUE TITLE
Hello World sample - == APP == Could not get state.

### ISSUE THREAD

**Issue by hugobarona** [dapr/samples#197]
## Expected Behavior
While running the Hello World sample, I did a few requests (POST and GET) to test the nodejs app. I would expect the requests to be able to access the statestore to persist or fetch orders.

## Actual Behavior

The POST is receiving the request and logging a new order, but then fails to persist state. And the GET request returns me a "Could not get state.". Apparently it is failing to access the state. 

## Steps to Reproduce the Problem

Followed the environment-setup guide to install dapr and I am running Dapr in standalone mode.
![dapr-state-issue](https://user-images.githubusercontent.com/5125006/80894469-16feb200-8cd3-11ea-8339-9a3bb0f31f37.PNG)

**Comment by msfussell** [comment]
@pruthvidhodda - can you follow up with this?

**Comment by hugobarona** [comment]
Hi @pruthvidhodda. It would be great to have some assistance on this during this week, since I am trying to finalize a session to deliver next week, related to Event-driven architecture and instead of presenting the traditional solutions with Azure Functions, Event Grid, Logic Apps, etc. I would like to maybe present a solution using Dapr and showing it in practice to the audience.

Thank you.

**Comment by amanbha** [comment]
@hugobarona With the dapr and app running, could you directly make the GET call to the state url
`http://localhost:<dapr-port>/v1.0/state/statestore/<key>`
Also could you share the statestore yaml from the components folder.

**Comment by hugobarona** [comment]
@amanbha I got the following response while trying to make a GET request for the statestore

{
    "errorCode": "ERR_STATE_STORE_NOT_CONFIGURED",
    "message": ""
}

The configuration for the statestore is the one available on the 1.hello world sample. I just downloaded the samples and followed the steps to test the first sample.

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
  - name: actorStateStore
    value: "true"

**Comment by amanbha** [comment]
@hugobarona thanks, could you also share the command you are using to run it and the output for it.

**Comment by hugobarona** [comment]
@amanbha follows info below:

command: 
`dapr run --app-id nodeapp --app-port 3000 --port 3500 node app.js`

logs:

`Starting Dapr with id nodeapp. HTTP Port: 3500. gRPC Port: 52256
== APP == Node App listening on port 3000!

== DAPR == time="2020-05-05T21:03:14.5058867+01:00" level=info msg="starting Dapr Runtime -- version 0.6.
0 -- commit e99f712-dirty" app_id=nodeapp instance=DESKTOP-BJD8BNP scope=dapr.runtime type=log ver=0.6.0        

== DAPR == time="2020-05-05T21:03:14.5058867+01:00" level=info msg="log level set to: info" app_id=nodeap
p instance=DESKTOP-BJD8BNP scope=dapr.runtime type=log ver=0.6.0

== DAPR == time="2020-05-05T21:03:14.5058867+01:00" level=info msg="metrics server started on :52257/" ap
p_id=nodeapp instance=DESKTOP-BJD8BNP scope=dapr.metrics type=log ver=0.6.0

== DAPR == time="2020-05-05T21:03:14.5107267+01:00" level=info msg="loading default configuration" app_id
=nodeapp instance=DESKTOP-BJD8BNP scope=dapr.runtime type=log ver=0.6.0

== DAPR == time="2020-05-05T21:03:14.5107267+01:00" level=info msg="standalone mode configured" app_id=no
deapp instance=DESKTOP-BJD8BNP scope=dapr.runtime type=log ver=0.6.0

== DAPR == time="2020-05-05T21:03:14.5107267+01:00" level=info msg="dapr id: nodeapp" app_id=nodeapp inst
ance=DESKTOP-BJD8BNP scope=dapr.runtime type=log ver=0.6.0

== DAPR == time="2020-05-05T21:03:14.5107267+01:00" level=info msg="mTLS is disabled. Skipping certificat
e request and tls validation" app_id=nodeapp instance=DESKTOP-BJD8BNP scope=dapr.runtime type=log ver=0.6.0     

== DAPR == time="2020-05-05T21:03:14.5117022+01:00" level=info msg="found component statestore (state.red
is)" app_id=nodeapp instance=DESKTOP-BJD8BNP scope=dapr.runtime type=log ver=0.6.0

== DAPR == time="2020-05-05T21:03:14.5117022+01:00" level=info msg="found component messagebus (pubsub.re
dis)" app_id=nodeapp instance=DESKTOP-BJD8BNP scope=dapr.runtime type=log ver=0.6.0

== DAPR == time="2020-05-05T21:03:14.5117022+01:00" level=info msg="application protocol: http. waiting o
n port 3000.  This will block until the app is listening on that port." app_id=nodeapp instance=DESKTOP-BJD8BNP 
scope=dapr.runtime type=log ver=0.6.0

== DAPR == time="2020-05-05T21:03:14.5126793+01:00" level=info msg="application discovered on port 3000" 
app_id=nodeapp instance=DESKTOP-BJD8BNP scope=dapr.runtime type=log ver=0.6.0

== DAPR == time="2020-05-05T21:03:23.831354+01:00" level=warning msg="error initializing state store stat
e.redis: redis store: error connecting to redis at localhost:6379: dial tcp [::1]:6379: connectex: No connection could be made because the target machine actively refused it." app_id=nodeapp instance=DESKTOP-BJD8BNP scope=dapr.runtime type=log ver=0.6.0

== DAPR == time="2020-05-05T21:03:23.831354+01:00" level=warning msg="either no actor state store or mult
iple actor state stores are specified in the configuration, actor stores specified: 0" app_id=nodeapp instance=DESKTOP-BJD8BNP scope=dapr.runtime type=log ver=0.6.0

== DAPR == time="2020-05-05T21:03:33.0755145+01:00" level=warning msg="error initializing pub sub pubsub.
redis: redis streams: error connecting to redis at localhost:6379: dial tcp [::1]:6379: connectex: No connection could be made because the target machine actively refused it." app_id=nodeapp instance=DESKTOP-BJD8BNP scope=dapr.runtime type=log ver=0.6.0

== DAPR == time="2020-05-05T21:03:33.0755145+01:00" level=info msg="Initialized service discovery to stan
dalone" app_id=nodeapp instance=DESKTOP-BJD8BNP scope=dapr.runtime type=log ver=0.6.0

== DAPR == time="2020-05-05T21:03:33.0755145+01:00" level=warning msg="actors: state store must be presen
t to initialize the actor runtime" app_id=nodeapp instance=DESKTOP-BJD8BNP scope=dapr.runtime.actor type=log ver=0.6.0

== DAPR == time="2020-05-05T21:03:33.0755145+01:00" level=warning msg="failed to init actors: state store
 does not support transactions which actors require to save state - please see https://github.com/dapr/docs" app_id=nodeapp instance=DESKTOP-BJD8BNP scope=dapr.runtime type=log ver=0.6.0

== DAPR == time="2020-05-05T21:03:33.0755145+01:00" level=info msg="enabled metrics grpc middleware" app_
id=nodeapp instance=DESKTOP-BJD8BNP scope=dapr.runtime.grpc type=log ver=0.6.0

== DAPR == time="2020-05-05T21:03:33.0755145+01:00" level=info msg="API gRPC server is running on port 52
256" app_id=nodeapp instance=DESKTOP-BJD8BNP scope=dapr.runtime type=log ver=0.6.0

== DAPR == time="2020-05-05T21:03:33.0755145+01:00" level=info msg="enabled metrics grpc middleware" app_
id=nodeapp instance=DESKTOP-BJD8BNP scope=dapr.runtime.grpc type=log ver=0.6.0

== DAPR == time="2020-05-05T21:03:33.0755145+01:00" level=info msg="internal gRPC server is running on po
rt 52261" app_id=nodeapp instance=DESKTOP-BJD8BNP scope=dapr.runtime type=log ver=0.6.0

== DAPR == time="2020-05-05T21:03:33.0755145+01:00" level=info msg="enabled cors http middleware" app_id=
nodeapp instance=DESKTOP-BJD8BNP scope=dapr.runtime.http type=log ver=0.6.0

== DAPR == time="2020-05-05T21:03:33.0755145+01:00" level=info msg="enabled proxy http middleware" app_id
=nodeapp instance=DESKTOP-BJD8BNP scope=dapr.runtime.http type=log ver=0.6.0

== DAPR == time="2020-05-05T21:03:33.0755145+01:00" level=info msg="enabled metrics http middleware" app_
id=nodeapp instance=DESKTOP-BJD8BNP scope=dapr.runtime.http type=log ver=0.6.0

== DAPR == time="2020-05-05T21:03:33.0755145+01:00" level=info msg="http server is running on port 3500" 
app_id=nodeapp instance=DESKTOP-BJD8BNP scope=dapr.runtime type=log ver=0.6.0

== DAPR == time="2020-05-05T21:03:33.0755145+01:00" level=info msg="local service entry announced" app_id
=nodeapp instance=DESKTOP-BJD8BNP scope=dapr.runtime type=log ver=0.6.0

== DAPR == time="2020-05-05T21:03:33.0755145+01:00" level=info msg="dapr initialized. Status: Running. In
it Elapsed 18564.787800000002ms" app_id=nodeapp instance=DESKTOP-BJD8BNP scope=dapr.runtime type=log ver=0.6.0  

Updating metadata for app command: node app.js
You're up and running! Both Dapr and your app logs will appear here.

== APP == Could not get state.

== APP == Got a new order! Order ID: 42

== APP == Failed to persist state.`

**Comment by amanbha** [comment]
@hugobarona I see following in output, is redis up and running.
error initializing state store state.redis: redis store: error connecting to redis at localhost:6379:

**Comment by LMWF** [comment]
If redis is not running (`docker ps`) you may have not run a `dapr init`.

**Comment by hugobarona** [comment]
![image](https://user-images.githubusercontent.com/5125006/81119618-09d80200-8f23-11ea-8e66-656fb0827c56.png)

I have the following containers running. So it looks like the redis container is running. And I did run the dapr init when I was setting up my environmnet.

**Comment by amanbha** [comment]
@hugobarona Is any other redis client able to connect to redis.

**Comment by hugobarona** [comment]
is there on the samples any client for the redis? I have no client here ready to test the connection.

**Comment by amanbha** [comment]
> is there on the samples any client for the redis? I have no client here ready to test the connection.

For troubleshooting, I wanted to try redis cli or any other third party tools. if you have VS code, you can use RedisXplorer

**Comment by hugobarona** [comment]
apparently there are issues related to connecting to the redis server on the container. I tried the redis Xplorer and also i created a quick nodejs redis client, and no luck. Any idea what can be? I also disabled the firewall in case it could be the port being blocked, but it is not the case as well.

**Comment by hugobarona** [comment]
but i was able to install the Redis Client (redis-cli) and connect to the local redis on port 6379. Followed this article - https://koukia.ca/installing-redis-on-windows-using-docker-containers-7737d2ebc25e

**Comment by hugobarona** [comment]
I tried to uninstall and install dapr again. both containers running, but when i try to run the 1. hello world sample, i get the following error:

== DAPR == time="2020-05-06T00:17:09.4920578+01:00" level=warning msg="error establishing client to place
ment service: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp [::1]:6050: connectex: No connection could be made because the target machine actively refused it.\"" app_id=nodeapp instance=DESKTOP-BJD8BNP scope=dapr.runtime.actor type=log ver=0.7.0

**Comment by pruthvidhodda** [comment]
sorry I missed the notifications for this thread, @hugobarona placement service is related to actors and you shouldn't be worried if you are trying to run 1.hello-world sample. Can you now check if the logs say:
```
level=info msg="found component statestore (state.redis)"
```

If so you should be able to save and get the state successfully.

**Comment by hugobarona** [comment]
It is working now. I believe it was maybe something related to the firewall at the beginning that somehow blocked the connection to the redis instance. Thank you for the help. I will try the samples on the next few days, so any question I will let you know.

**Comment by amanbha** [comment]
> but i was able to install the Redis Client (redis-cli) and connect to the local redis on port 6379. Followed this article - https://koukia.ca/installing-redis-on-windows-using-docker-containers-7737d2ebc25e

Yes, this would have worked as cli and redis both are running in the docker network.
