### ISSUE TITLE
dapriosamples/hello-k8s-node:edge as used in sample "2.hello-kubernetes" fails with Dapr 0.8.0 as DAPR_HTTP_PORT and DAPR_GRPC_PORT isn't set

### ISSUE THREAD

**Issue by HansK-p** [dapr/samples#251]
## Expected Behavior
After deployment of the sample application it's expected that the nodeapp pod is able to receive and persist orders.

## Actual Behavior
Fetching orders seems to work, while persisting them seems to fail. Extract from nodeapp logg:
<pre>
Got a new order! Order ID: 196
{ FetchError: request to http://localhost:undefined/v1.0/state/statestore failed, reason: connect ECONNREFUSED 127.0.0.1:80
</pre>

## Steps to Reproduce the Problem
install K8s v 1.18.5

install dapr
<pre>
helm repo add dapr https://daprio.azurecr.io/helm/v1/repo
helm repo update
kubectl create namespace dapr-system

helm install dapr dapr/dapr --namespace dapr-system
</pre>

Install redis
<pre>
kubectl create namespace dapr-redis

helm repo add stable https://kubernetes-charts.storage.googleapis.com
helm repo update

helm install redis stable/redis --namespace dapr-redis
</pre>

Install the dapr demo
<pre>
redispwd="$(kubectl get secret --namespace dapr-redis redis -o jsonpath="{.data.redis-password}" | base64 --decode)"
cp -vf "${HOME}/git/dapr/samples/2.hello-kubernetes/deploy/"*.yaml DaprTestApplicaton/
kustomize build DaprTestApplicaton |\
  sed "s:YOUR_REDIS_HOST_HERE:redis-master.dapr-redis.svc.cluster.local:" |\
  sed "s:YOUR_REDIS_KEY_HERE:$redispwd:" |\
  kubectl apply -f -
</pre>

The kustomize file
<pre>
resources:
- 00_namespace.yaml
- node.yaml
- python.yaml
- redis.yaml

namespace: dapr-hello
</pre>

## The problem
Seems the the node app (dapriosamples/hello-k8s-node:edge) only works if the following environment variables are set in the deployment:
<pre>
      env:
      - name: DAPR_HTTP_PORT 
        value: "3500"
      - name: DAPR_GRPC_PORT 
        value: "50001"
</pre>
I'm pretty sure this demo worked with an earlier Dapr + K8s version, but I haven't verified this.

Ref also https://github.com/dapr/dapr/issues/1637.

**Comment by pruthvidhodda** [comment]
@HansK-p the samples in master branch will work with edge version of dapr. If you are using 0.8.0 dapr runtime version then please checkout [v0.8.0 tag for samples](https://github.com/dapr/samples/tree/v0.8.0).

**Comment by HansK-p** [comment]
@pruthvidhodda That sounds like a good explanation. Does this mean that the documentation should be updated?

I assume one ends up with a broken demo both when following https://github.com/dapr/samples/tree/v0.8.0/2.hello-kubernetes and when following https://github.com/dapr/samples/tree/master/2.hello-kubernetes.

Is it an option to change the Prerequisites part of the "hello kubernetes" document from:
<pre>
git clone https://github.com/dapr/samples.git
cd samples
</pre>

to
<pre>
git clone -b v0.8.0 https://github.com/dapr/samples.git
cd samples
</pre>
When in the v0.8.0 branche of the samples documentation, or just simply use something like:

<pre>
git clone -b &ltdapr_version_tag&gt https://github.com/dapr/samples.git
cd samples
</pre>

I tried googling "dapr hello kubernetes" and ended up in the master branch documentation.

**Comment by pruthvidhodda** [comment]
> I assume one ends up with a broken demo both when following https://github.com/dapr/samples/tree/v0.8.0/2.hello-kubernetes and when following https://github.com/dapr/samples/tree/master/2.hello-kubernetes.

Why do you think following https://github.com/dapr/samples/tree/v0.8.0/2.hello-kubernetes would lead to broken demo?

**Comment by HansK-p** [comment]
@pruthvidhodda Because it broke when I followed the documentation :).

I ended up with a nodeapp deployment which uses the dapriosamples/hello-k8s-node:edge docker image. And that image doesn't work with dapr v.0.8.0, ref your first comment. At least it didn't work for me.

<pre>
$ git clone https://github.com/dapr/samples.git
Cloning into 'samples'...
remote: Enumerating objects: 42, done.
remote: Counting objects: 100% (42/42), done.
remote: Compressing objects: 100% (38/38), done.
remote: Total 1587 (delta 11), reused 10 (delta 4), pack-reused 1545
Receiving objects: 100% (1587/1587), 9.04 MiB | 854.00 KiB/s, done.
Resolving deltas: 100% (876/876), done.
$ cd samples
$ grep image 2.hello-kubernetes/deploy/node.yaml 
        image: dapriosamples/hello-k8s-node:edge
        imagePullPolicy: Always
</pre>

I now know that I should have done:
<pre>
$ git clone -b v0.8.0 https://github.com/dapr/samples.git
Cloning into 'samples'...
remote: Enumerating objects: 42, done.
remote: Counting objects: 100% (42/42), done.
remote: Compressing objects: 100% (38/38), done.
remote: Total 1587 (delta 11), reused 10 (delta 4), pack-reused 1545
Receiving objects: 100% (1587/1587), 9.04 MiB | 823.00 KiB/s, done.
Resolving deltas: 100% (876/876), done.
Note: switching to 'bf05a9c44a7a195392618e6e4a5d1dbe7102b16c'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

$ cd samples
$ grep image 2.hello-kubernetes/deploy/node.yaml 
        image: dapriosamples/hello-k8s-node:0.8.0
        imagePullPolicy: Always
</pre>

**Comment by pruthvidhodda** [comment]
> > I assume one ends up with a broken demo both when following https://github.com/dapr/samples/tree/v0.8.0/2.hello-kubernetes and when following https://github.com/dapr/samples/tree/master/2.hello-kubernetes.
> 
> Why do you think following https://github.com/dapr/samples/tree/v0.8.0/2.hello-kubernetes would lead to broken demo?

Sorry if I wasn't clear but my intention is to say that v0.8.0 version of samples should work and won't break if you are using the same version of dapr runtime.

I agree that it's easy to miss checking out the correct version of samples but I don't think it needs any changes. Right now we mention about compatible versions [here](https://github.com/dapr/samples#supported-dapr-runtime-version) in the samples repo.

**Comment by HansK-p** [comment]
Hello

I must admit that I disagree. I personally prefer demos where one can follow the documentation blindly in order to get a working result.. This time I didn't even think about checking out a specific branch as I just used copied and pasted the commands exactly as they are written in the documentation. That's how I usually do it when running these kind of demos. If something fails, I usually double-check that I've actually followed the documentation, troubleshoot further if the demo still doesn't work (or just give up) and sometimes I inform the maintainers that there are issues.

Personally I would prefer that the documentation was updated so that it is obvious that the master branch should not be used, even though that is what currently happens if one follows the documentation (copy/paste with only obvious modifications if any). But I must admit that I'm not a developer and might not be a part of the intended audience.

Br

Hans K.

**Comment by pruthvidhodda** [comment]
Fair point!

I like your idea here:
> just simply use something like:
> 
> git clone -b <dapr_version_tag> https://github.com/dapr/samples.git
> cd samples

Something like:
```
If using edge version of dapr:
git clone https://github.com/dapr/samples.git
cd samples/1.hello-world

If using specific version of dapr:
git clone -b <dapr_version_tag> https://github.com/dapr/samples.git
cd samples/1.hello-world
```

Is this okay @amanbha ?

**Comment by HansK-p** [comment]
At least it would make me happy if such a change is made to the documentation :).

Even the command:
<pre>
$ wget -q https://raw.githubusercontent.com/dapr/cli/master/install/install.sh -O - | /bin/bash
Your system is linux_amd64
Installing Dapr CLI...

Downloading https://github.com/dapr/cli/releases/download/v0.8.0/dapr_linux_amd64.tar.gz ...
</pre>
does download the latest released version of Dapr and not the edge version. Ref https://github.com/dapr/docs/blob/master/getting-started/environment-setup.md#installing-dapr-on-a-kubernetes-cluster

So I'd guess that people trying the demo will almost never use the edge version of Dapr. Which means that checking out a specific branch should be the norm and not the exception when running these demos?

I also assume that one has to build the binaries by hand in order to use the dapr edge version?

Br

Hans K.

**Comment by pruthvidhodda** [comment]
That's right, we have to build the binaries for edge version.

Adding a line in the documentation of each sample pointing to [this table](https://github.com/dapr/samples#supported-dapr-runtime-version) and an instruction to checkout the tag(<dapr_version_tag>) should work in my opinion. Thoughts on this?

Are you interested in making this contribution to dapr?

**Comment by HansK-p** [comment]
Hello

I'm really bad with git, but I can have a try within a few days.

I "finally" found out that there is an image "docker.io/daprioedge" which is used by at least the Docker Compose sample (https://github.com/dapr/samples/tree/master/10.hello-docker-compose).
* I tried using the edge image in K8s using Helm and only modifying the image tag, and that failed (dapr-operator failed). Probably has the Helm chart itself would have needed an update for the Dapr edge image to work
* I will not make changes to the docker-edge sample documentation as I assume that will only create confusions

So this finding doesn't really change anything.

Br

Hans K.

**Comment by HansK-p** [comment]
I tried to squash my commits - and things started failing in interesting ways (= my git skills are really not good).

Can you still have a look at the result? It's not exactly what you asked for, but might still be ok (https://github.com/HansK-p/samples/tree/git-clone-supply-version-tag). I'll fix the squash thing in one way or another when things are looking ok.

**Comment by pruthvidhodda** [comment]
Closed with [this](https://github.com/dapr/samples/pull/255) PR
