### ISSUE TITLE
Add external project eShopOnDapr

### ISSUE THREAD

**Issue by georgestevens99** [dapr/samples#60]
Is it possible to add this https://github.com/dotnet-architecture/eShopOnDapr  to the External Samples?  It is the code sample for the Microsoft free ebook  "Dapr for .NET Developers" https://docs.microsoft.com/en-us/dotnet/architecture/dapr-for-net-developers/ 

Not only does this book have lots of code examples, but it also shows how to use Visual Studio to make containers and then run them with Docker Compose and allows debugging with Visual Studio.  All this uses the Visual Studio tooling which makes things much easier!  Thanks.

**Comment by willvelida** [comment]
@georgestevens99 @msfussell - I've raised a PR for this. Let me know if you have any feedback, or I've missed anything :)

**Comment by msfussell** [comment]
Added.
