### ISSUE TITLE
Emphasis on multiple languages

### ISSUE THREAD

**Issue by markgar** [dapr/samples#65]
These samples tend to emphasize the fact that dapr is multi-language neutral and include multiple languages in the sample.

The distributed calculator requires downloading and installing multiple languages just to get going.  I see this as a potential barrier.

Would there be a chance of having distributed calculator samples that are only one language as well as the one that shows all the languages?  This way we can chose which one resonates more - one that emphasizes that using HTTP and gRPC provides language disintermediation and one that makes it easy for someone who only uses one language and would like a simplified sample.

**Comment by ecw1973** [comment]
I agree with this.   The samples are less useful to me because I want to focus on .Net and don't care about outher languages right now.

**Comment by paulyuk** [comment]
Hey @markgar  and @ecw1973 there is an approved proposal lead by @greenie-msft  to create a new batch of quickstarts that will be completed for each of the languages (vs. one sample mixing and matching, or being random).  There is a plan for these to be 2+ services in each to show interactions.  Please see more in the STC meeting minutes here: https://github.com/dapr/community/issues/120

Would that start to address the issue?  Is there something about distributed calculator that is special, just so I understand?

**Comment by markgar** [comment]
For me, yes.  I wanted a quickstart where I didn't need to know 3 languages.  I'm a dotnet dev and I don't really want to have to get node or rust or python working just to get going with a complete quickstart.

**Comment by markgar** [comment]
@paulyuk, I know that multi language is a really interesting capability of dapr, but I don't think most enterprises come to dapr for this reason.  So having both kinds of quickstarts will be beneficial.

**Comment by msfussell** [comment]
The new quickstarts addressed the single language issue. Closing
