### ISSUE TITLE
1.hello-world example BODY orderId property not correctly set in document

### ISSUE THREAD

**Issue by furkansakar** [dapr/samples#71]
In 1.hello-world example, after execution of the following POST request:
http://localhost:3500/v1.0/invoke/mynode/method/neworder

## Expected Behavior

== Got a new order! Order ID: 42

## Actual Behavior

== Got a new order! Order ID: undefined

## Steps to Reproduce the Problem

Run the example in 1.hello-world and use same BODY raw value in the following POST request
http://localhost:3500/v1.0/invoke/mynode/method/neworder

## How to solve the problem

Use "orderId" instead of "orderID" when preparing the POST request

**Comment by ryanvolum** [comment]
This should be fixed by #74. The problem seems to have been the Postman screenshot using the wrong casing for the orderId. Please reopen if the issue persists!
