### ISSUE TITLE
2.hello-kubernetes: ExternalIP pending

### ISSUE THREAD

**Issue by JensKula** [dapr/samples#75]
External IP of nodeapp stays pending for several hours located in Germany see:
Kubectl get svc nodeapp
NAME      TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
nodeapp   LoadBalancer   10.98.150.231   <pending>     80:31535/TCP   17h

**Comment by davlinski** [comment]
You probably have another service running on port 80 (which typically happens as you are running through the samples and not shutting down things down as you move on).

**Comment by youngbupark** [comment]
@JensKula Can you please give us more information about your cluster? We have tested that samples in MiniKube and AKS.

**Comment by artursouza** [comment]
Is this issue still going on?

**Comment by jekula** [comment]
@artursouza  No, it was related to minikube and now it is mentioned minicube won´t get an external ip. Sorry for the late reply, I lost focus on this as I moved executing samples on AKS due to the helm issues.

**Comment by youngbupark** [comment]
Closing.
