### ISSUE TITLE
Application logs in pub-sub sample have empty payload {}

### ISSUE THREAD

**Issue by abhirockzz** [dapr/samples#79]
I was trying out the pub-sub sample.

## Expected Behavior

In response to `dapr publish --topic A --payload '{ "message": "This is a test" }'`, the [pub-sub sample](https://github.com/dapr/samples/tree/master/4.pub-sub) logs should be something like `[0m?[94;1m== APP == Topic A: { id: '5780e2ca-f526-4839-92e5-a0a30aff829a', source: 'react-form', type: 'com.dapr.event.sent', specversion: '0.3',data: { message: 'this is a test' } }` (as per docs)

## Actual Behavior

What I see is the following: `APP == A:  {}`

## Steps to Reproduce the Problem

- git clone https://github.com/dapr/samples
- cd node-subscriber
- npm install
- dapr run --app-id node-subscriber --app-port 3000 node app.js
- dapr publish --topic A --payload '{ "message": "This is a test" }'

**Comment by MohsenMahdieh** [comment]
> I was trying out the pub-sub sample.
> 
> ## Expected Behavior
> In response to `dapr publish --topic A --payload '{ "message": "This is a test" }'`, the [pub-sub sample](https://github.com/dapr/samples/tree/master/4.pub-sub) logs should be something like `[0m?[94;1m== APP == Topic A: { id: '5780e2ca-f526-4839-92e5-a0a30aff829a', source: 'react-form', type: 'com.dapr.event.sent', specversion: '0.3',data: { message: 'this is a test' } }` (as per docs)
> 
> ## Actual Behavior
> What I see is the following: `APP == A: {}`
> 
> ## Steps to Reproduce the Problem
> * git clone https://github.com/dapr/samples
> * cd node-subscriber
> * npm install
> * dapr run --app-id node-subscriber --app-port 3000 node app.js
> * dapr publish --topic A --payload '{ "message": "This is a test" }'

Same Issue here.

**Comment by MohsenMahdieh** [comment]
@youngbupark would you be able to have a look at this issue mate?

**Comment by youngbupark** [comment]
@MohsenMahdieh Sorry for your inconvenience. The bug is fixed by #85. Please pull the repo and try out pubsub again. please let us know if you find anything wrong.

**Comment by youngbupark** [comment]
Thanks for your contribution!

**Comment by youngbupark** [comment]
@abhirockzz Please pull the sample repo again and let us know.

**Comment by abhirockzz** [comment]
Yes it's fixed! This is what I see in the logs

```
== APP == A:  {
== APP ==   id: 'fd69cbae-3f59-46d0-8704-80e09c513615',
== APP ==   source: 'node-subscriber',
== APP ==   type: 'com.dapr.event.sent',
== APP ==   specversion: '0.3',
== APP ==   datacontenttype: 'application/json',
== APP ==   data: { message: 'This is a test' }
== APP == }
```

**Comment by youngbupark** [comment]
@abhirockzz Great! Thanks for the reporting. This sample was broken by the change right after we announced v0.1.0 Dapr. We tag the version to sample to avoid this situation.
