### ISSUE TITLE
Inaccurate references to Azure Event Hubs in bindings sample

### ISSUE THREAD

**Issue by abhirockzz** [dapr/samples#87]
Dapr [bindings sample](https://github.com/dapr/samples/tree/master/5.bindings) has couple of references to Azure Event Hubs

1. "... We'll bind to Kafka and Event Hub..."
2.  "... This sample also includes a manifest for using Azure Event Hubs ..."

I don't think this is accurate. 

1. Kafka binding cannot be used with Event Hubs (Kafka endpoint) since current binding does not support authentication
2. the sample does not include Azure Event Hubs related manifest

**Comment by ryanvolum** [comment]
Thanks @abhirockzz - I believe that the plan was originally intended to also include an Event Hubs manifest. @youngbupark, is there a near-term plan to roll this in? If not, I'm happy to pull out the EH references.

**Comment by youngbupark** [comment]
@ryanvolum / we decide to not include EH sample to binding sample before releasing 0.1.0.

@abhirockzz thanks for your contribution. We love to see your sample :)
