### ISSUE TITLE
Azure Event Hubs bindings example

### ISSUE THREAD

**Issue by abhirockzz** [dapr/samples#88]
## Describe the proposal

Sample app to demonstrate bindings with Azure Event Hubs bindings example

**Comment by abhirockzz** [comment]
work in progress...

**Comment by abhirockzz** [comment]
Hit issue #91 while working on [this example](https://github.com/abhirockzz/dapr-eventhubs-bindings)

**Comment by RicardoNiepel** [comment]
As you have closed #91 what's the status of your example?

Can we try to include it as an official one / following the original plan for making Kafka/Event Hubs exchangeable at https://github.com/dapr/samples/tree/master/5.bindings ?

**Comment by abhirockzz** [comment]
I am still working on the example. But it will still not be able to "interchange" the usage of any Kafka cluster and Azure Event Hubs since the Kafka binding component does not support authentication (it's required for Event Hubs). This is merged via #77 but not integrated end to end with Dapr runtime

**Comment by amanbha** [comment]
@abhirockzz Are you still working on this one?

**Comment by abhirockzz** [comment]
Here is an example https://github.com/abhirockzz/dapr-kafka-eventhubs-bindings

**Comment by msfussell** [comment]
This is generally covered here https://github.com/dapr/docs/tree/master/howto/send-events-with-output-bindings in the HowTos. We are also going to focus on creating a language specific set of docs
