### ISSUE TITLE
4.pub-sub Node Subscriber doesn't receive request body

### ISSUE THREAD

**Issue by ryanvolum** [dapr/samples#96]
## Expected Behavior

When running the pubsub sample in Kubernetes and manufacturing messages with the react front-end, the node subscriber receives messages, but no message body.
## Actual Behavior

The node subscriber prints the topic name with an empty body:

```bash
A: {}
```

## Steps to Reproduce the Problem

Run the sample in kubernetes and log the node-subscriber's output. 

## Culprit

The source of the problem seems to be the json type that the express bodyParser is using: `application/*+json`. When changed to `application/json`, the sample works as expected. Apparently, however, this causes issues in standalone mode: #79, which @youngbupark noted in #85.

**Comment by ryanvolum** [comment]
@abhirockzz FYI

**Comment by youngbupark** [comment]
@ryanvolum @abhirockzz this issue must be fixed. I tested in standalone and k8s envs.

**Comment by ryanvolum** [comment]
@youngbupark did you test it with the react front-end? I wonder if maybe the issue is the way that it's posting messages.

I'm definitely not seeing the content of topics of type A. I'll check again to be sure.

**Comment by youngbupark** [comment]
@ryanvolum yeah I tested with react front-end.

**Comment by youngbupark** [comment]
@ryanvolum please look at this conversation. - https://gitter.im/Dapr/samples?at=5db71ad714d55a378590324e

It was working in minikube.

**Comment by ryanvolum** [comment]
Upon updating to the latest Dapr version, this no longer appears to be an issue.
