### ISSUE TITLE
dapr init --slim gives me - error moving dashboard.exe binary to path: rename

### ISSUE THREAD

**Issue by AvtsVivek** [dapr/samples#97]
I am trying to do [this dapr slim sample](https://github.com/dapr/samples/tree/master/hello-dapr-slim).

I ensure a clean slate by running dapr uninstall --all.

Then I start with [the first step of Slim Init](https://github.com/dapr/samples/tree/master/hello-dapr-slim#step-1---setup-dapr-slim-init).

`error moving dashboard.exe binary to path: rename C:\Users\UserName\.dapr\bin\release\windows_amd64\dashboard.exe C:\Users\UserName\.dapr\bin\dashboard.exe: Access is denied.`

Note below I am running powershell as administrator.

![image](https://user-images.githubusercontent.com/41255281/150289490-5b9257fb-3297-4507-841e-255a115186bf.png)

What am I missing?

**Comment by AvtsVivek** [comment]
Ok, I think I understood the problem.

While I ensured a clean slate by running dapr uninstall --all, I noticed dapr dashboard is still running in the background.

When I run **dapr uninstall --all** I feel dapr dashboard, if its running, must be also be stopped.

**Comment by shubham1172** [comment]
@AvtsVivek can you please close this issue and create an issue with the [CLI repository](https://github.com/dapr/cli/issues)?

**Comment by msfussell** [comment]
Close issue
